model:
    arch: depth
data:
    dataset: cityscapes
    train_split: assets/train.csv
    valid_split: assets/val.csv
    max_depth: 80
training:
    train_iters: 40
    batch_size: 1
    val_interval: 20
    print_interval: １
    optimizer:
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0001
    l_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    resume: 'runs/icnet-seg/413/depth_cityscapes_best_model.pkl'
    visdom: False
    device: cpu
seed: 1103
measure_time: True
