model:
    arch: depth
data:
    dataset: cityscapes
    train_split: assets/train.csv
    valid_split: assets/val.csv
    max_depth: 80
training:
    train_iters: 80000
    batch_size: 4
    val_interval: 500
    print_interval: 25
    optimizer:
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0001
    l_schedule:
    momentum: 0.99
    weight_decay: 0.0005
#    resume: 'runs/icnet-seg/308/depth_cityscapes_best_model.pkl'
    resume: 'runs/icnet-seg/413/depth_cityscapes_best_model.pkl'
    visdom: False
    device: cuda
seed: 1103
measure_time: True
