model:
    arch: depth
data:
    dataset: cityscapes
    train_split: assets/train.csv
    valid_split: assets/val.csv
    max_depth: 400
training:
    train_iters: 15000
    batch_size: 8
    val_interval: 250
    print_interval: 25
    optimizer:
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0001
    l_rate: 1.0e-4
    l_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    # resume: runs/icnet-depth./1103/depth_cityscapes_best_model.pkl
    resume:
    visdom: False
    device: cuda
seed: 1103
measure_time: True