model:
    arch: depth
data:
    dataset: cityscapes
    train_split: assets/train.csv
    valid_split: assets/val.csv
    max_depth: 80
training:
    train_iters: 150
    batch_size: 1
    val_interval: 25
    print_interval: 1
    optimizer:
        lr: 1.0e-4
    l_rate: 1.0e-4
    l_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    # resume: runs/icnet-depth./1103/depth_cityscapes_best_model.pkl
    resume:
    visdom: False
    device: cuda
seed: 1103
measure_time: True